/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.ClsCamara;
import Clases.ClsConnection;
import Clases.ClsReloj;
import Clases.ClsUsuario;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Samuel David Ortiz
 */
public class FrmNuevoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form FrmNuevoUsuario
     */
    private ClsCamara camara;
    ClsReloj reloj = new ClsReloj();

    private boolean validador;
    private String mensaje;

    public FrmNuevoUsuario() {
        initComponents();

        reloj.setLblReloj(lblReloj);
        reloj.start();
        this.txtCodigo.setText(generarCodigo());
    }

    private String generarCodigo() {
        Date date = new Date();
        SimpleDateFormat DateFor = new SimpleDateFormat("yyyyMMddHHmmss");

        return DateFor.format(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblReloj = new javax.swing.JLabel();
        pnlDatos = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        pnlDatos1 = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblEspacio1 = new javax.swing.JLabel();
        lblEspacio2 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        lblNombre2 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JTextField();
        lblApellido1 = new javax.swing.JLabel();
        txtApellido1 = new javax.swing.JTextField();
        lblApellido2 = new javax.swing.JLabel();
        txtApellido2 = new javax.swing.JTextField();
        lblNac = new javax.swing.JLabel();
        txtNac = new javax.swing.JTextField();
        lblEspacio3 = new javax.swing.JLabel();
        lblEspacio4 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContra1 = new javax.swing.JLabel();
        txtContra1 = new javax.swing.JPasswordField();
        lblEspacio5 = new javax.swing.JLabel();
        lblEspacio6 = new javax.swing.JLabel();
        lblContra2 = new javax.swing.JLabel();
        txtContra2 = new javax.swing.JPasswordField();
        chkIniciarCamara = new javax.swing.JCheckBox();
        pnlBotones = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/umg.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NUEVO USUARIO");

        lblReloj.setBackground(new java.awt.Color(184, 242, 230));
        lblReloj.setFont(new java.awt.Font("Dubai Medium", 1, 36)); // NOI18N
        lblReloj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReloj.setText("00:00:00");
        lblReloj.setOpaque(true);

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
                    .addGroup(pnlTituloLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(pnlTituloLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pinwi.png"))); // NOI18N
        lblImagen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagenMouseClicked(evt);
            }
        });

        pnlDatos1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCodigo.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        lblCodigo.setText("Código");
        pnlDatos1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 224, 45));

        txtCodigo.setEditable(false);
        pnlDatos1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 0, 224, 45));
        pnlDatos1.add(lblEspacio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 0, 224, 45));
        pnlDatos1.add(lblEspacio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 0, 224, 45));

        lblNombre1.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        lblNombre1.setText("Primer Nombre");
        pnlDatos1.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 224, 45));
        pnlDatos1.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 60, 224, 45));

        lblNombre2.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        lblNombre2.setText("Segundo Nombre");
        pnlDatos1.add(lblNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 60, 224, 45));

        txtNombre2.setPreferredSize(new java.awt.Dimension(85, 29));
        pnlDatos1.add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 224, 45));

        lblApellido1.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        lblApellido1.setText("Primer Apellido");
        pnlDatos1.add(lblApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 224, 45));
        pnlDatos1.add(txtApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 120, 224, 45));

        lblApellido2.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        lblApellido2.setText("Segundo Apellido");
        pnlDatos1.add(lblApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 120, 224, 45));
        pnlDatos1.add(txtApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 224, 45));

        lblNac.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        lblNac.setText("Fecha de Nacimiento");
        pnlDatos1.add(lblNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 224, 45));
        pnlDatos1.add(txtNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 180, 224, 45));
        pnlDatos1.add(lblEspacio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 180, 224, 45));
        pnlDatos1.add(lblEspacio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 180, 224, 45));

        lblUsuario.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        lblUsuario.setText("Usuario");
        pnlDatos1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 224, 45));
        pnlDatos1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 240, 224, 45));

        lblContra1.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        lblContra1.setText("Contraseña");
        pnlDatos1.add(lblContra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 240, 224, 45));

        txtContra1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContra1KeyReleased(evt);
            }
        });
        pnlDatos1.add(txtContra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 224, 45));
        pnlDatos1.add(lblEspacio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 224, 45));
        pnlDatos1.add(lblEspacio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 300, 224, 45));

        lblContra2.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
        lblContra2.setText("Confirmar Contraseña");
        pnlDatos1.add(lblContra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 300, 224, 45));
        pnlDatos1.add(txtContra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 224, 45));

        chkIniciarCamara.setText("jCheckBox1");
        chkIniciarCamara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIniciarCamaraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkIniciarCamara)
                    .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosLayout.createSequentialGroup()
                    .addContainerGap(226, Short.MAX_VALUE)
                    .addComponent(pnlDatos1, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chkIniciarCamara)
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlDatosLayout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(pnlDatos1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );

        pnlBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrear.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        pnlBotones.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 200, 60));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 200, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtContra1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContra1KeyReleased
        this.txtContra2.setVisible(true);
        this.lblContra2.setVisible(true);
    }//GEN-LAST:event_txtContra1KeyReleased

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        ClsUsuario usuario = new ClsUsuario();

        String pass = null;
        String pass2 = null;
        //ackgroundImage1 back = new BackgroundImage1();

        validarCampos();

        if (!isValidador()) {
            if (String.valueOf(txtContra1.getPassword()).equals(String.valueOf(txtContra2.getPassword()))) {
                pass = String.valueOf(txtContra1.getPassword());
                pass2 = String.valueOf(txtContra2.getPassword());

                try {
                    ClsConnection cn = new ClsConnection();
                    cn.conexion("BasesDeDatos1", "umg", "1234");

                    String query = "INSERT INTO `basesdedatos1`.`usuarios` (`codigo`, `nombre1`,`nombre2`,`apellido1`,`apellido2`,`fechaNac`,`usuario`,"
                            + " `contraseña`, urlFoto) VALUES("
                            + "'" + txtCodigo.getText() + "',"
                            + "'" + txtNombre1.getText() + "',"
                            + "'" + txtNombre2.getText() + "',"
                            + "'" + txtApellido1.getText() + "',"
                            + "'" + txtApellido2.getText() + "',"
                            + "'" + txtNac.getText() + "',"
                            + "'" + txtUsuario.getText() + "',"
                            + "'" + pass + "',"
                            + "'./src/Images/Fotos/" + txtCodigo.getText() + ".jpg'"
                            + ");";

                    cn.insert(query);

                    usuario.nuevoUsuario(txtCodigo.getText(), txtNombre1.getText(), txtNombre2.getText(), txtApellido1.getText(), txtApellido2.getText(),
                            txtNac.getText(), txtUsuario.getText(), pass, pass2,
                            "./src/Images/Fotos/U " + txtCodigo.getText() + ".jpg");

                    //borrarTextos();

                    JOptionPane.showMessageDialog(null, "Usuario creado exitosamente");

                    cn.close();

                } catch (Exception e) {

                }

            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden\nIntente de nuevo", "Adverventcia",
                        JOptionPane.WARNING_MESSAGE);

                this.txtContra1.requestFocus();
            }
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void chkIniciarCamaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIniciarCamaraActionPerformed
        if (chkIniciarCamara.isSelected()) {
            camara = new ClsCamara(this.lblImagen);
            camara.start();
        }

        if (!chkIniciarCamara.isSelected()) {
            camara.DetenerVideo();
            camara.stop();
            lblImagen.setIcon(null);
        }

        //this.btnSeleccionarImagen.setEnabled(!this.chkIniciarCamara.isSelected());
    }//GEN-LAST:event_chkIniciarCamaraActionPerformed

    private void lblImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagenMouseClicked
        new FrmFoto(this.txtCodigo.getText(), this.lblImagen).setVisible(true);
    }//GEN-LAST:event_lblImagenMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        reloj.stop();
    }//GEN-LAST:event_btnCancelarActionPerformed

    public void validarCampos() {
        setMensaje("");
        setValidador(false);

        String[] image = lblImagen.getIcon().toString().split("/");

        if (image[image.length - 1].equals("pinwi.png")) {
            setMensaje(getMensaje() + "La fotografía no puede estar vacia.\n");
        }

        if (txtCodigo.getText().equals("")) {
            setMensaje(getMensaje() + "El campo " + lblCodigo.getText() + " no puede estar vacio.\n");
        }
        if (txtNombre1.getText().equals("")) {
            setMensaje(getMensaje() + "El campo " + lblNombre1.getText() + " no puede estar vacio.\n");
        }
        /*if (txtNombre2.getText().equals("")) {
            mensaje += "El campo " + lblNombre2.getText() + " no puede estar vacio.\n";
        }*/
        if (txtApellido1.getText().equals("")) {
            setMensaje(getMensaje() + "El campo " + lblApellido1.getText() + " no puede estar vacio.\n");
        }
        /*if (txtApellido2.getText().equals("")) {
            mensaje += "El campo " + lblApellido2.getText() + " no puede estar vacio.\n";
        }*/
        if (txtNac.getText().equals("")) {
            setMensaje(getMensaje() + "El campo " + lblNac.getText() + " no puede estar vacio.\n");
        }
        if (txtUsuario.getText().equals("")) {
            setMensaje(getMensaje() + "El campo " + lblUsuario.getText() + " no puede estar vacio.\n");
        }
        if (String.valueOf(txtContra1.getPassword()).equals("")) {
            setMensaje(getMensaje() + "El campo " + lblContra1.getText() + " no puede estar vacio.\n");
        }

        if (!mensaje.equals("")) {
            JOptionPane.showMessageDialog(null, "Error\n\n" + this.getMensaje());
        } else {
            setValidador(true);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNuevoUsuario().setVisible(true);
            }
        });
    }

    public boolean isValidador() {
        return validador;
    }

    public void setValidador(boolean validador) {
        this.validador = validador;
    }

    public String getMensaje() {
        return mensaje;
    }

    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JCheckBox chkIniciarCamara;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblApellido2;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblContra1;
    private javax.swing.JLabel lblContra2;
    private javax.swing.JLabel lblEspacio1;
    private javax.swing.JLabel lblEspacio2;
    private javax.swing.JLabel lblEspacio3;
    private javax.swing.JLabel lblEspacio4;
    private javax.swing.JLabel lblEspacio5;
    private javax.swing.JLabel lblEspacio6;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNac;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblReloj;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlDatos1;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JPasswordField txtContra1;
    private javax.swing.JPasswordField txtContra2;
    private javax.swing.JTextField txtNac;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
